ALTER TABLE experts DISABLE ROW LEVEL SECURITY;
ALTER TABLE expert_profile DISABLE ROW LEVEL SECURITY;
ALTER TABLE interview_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE homework_ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_blueprints DISABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_chunks DISABLE ROW LEVEL SECURITY;
